### ISSUE TITLE
Warning during most operations

### ISSUE THREAD

**Issue by ehelms** [redhataccess/foreman-plugin#10]
I am seeing the following output when running most command line operations such as db:migrate or db:seed.

```
/opt/theforeman/tfm/root/usr/share/gems/gems/redhat_access-2.0.3/app/services/redhat_access/telemetry/look_ups.rb:171: warning: key :hosts is duplicated and overwritten on line 172
```

**Comment by lphiri** [comment]
I am aware of this one.  Fixed on another branch and need to be pulled into next release.
