### ISSUE TITLE
Insights playbook remediation fails for hosts with uppercase hostname

### ISSUE THREAD

**Issue by snagoor** [redhataccess/foreman-plugin#39]
Registering hosts with uppercase `CLIENT.example.com` to insights and remediation through Ansible Playbook fails with error **Failed to create job. Ensure your systems are registered in Foreman**. 

Registering hosts to Katello (using subscription-manager), hosts are created in Foreman as lower case `client.example.com` and same host registered to insights gets registered using the actual hostname `CLIENT.example.com` and when we try to lookup [https://github.com/redhataccess/foreman-plugin/blob/2cfda5a4bc2c08dad40d367c1ef22791c895efdf/redhat-access/app/models/redhat_access/concerns/host_managed_extensions.rb#L15](https://github.com/redhataccess/foreman-plugin/blob/2cfda5a4bc2c08dad40d367c1ef22791c895efdf/redhat-access/app/models/redhat_access/concerns/host_managed_extensions.rb#L15) 

Always `nil` value is returned for these hosts.

**Comment by ares** [comment]
Thanks Nagoor, is there a tracking BZ?

**Comment by snagoor** [comment]
Hi Marek, yes at this moment we are referencing this [BZ # 1684454](https://bugzilla.redhat.com/show_bug.cgi?id=1684454), which
